Refactor: update `test-coverage` workflow

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -24,7 +24,7 @@ jobs:
     steps:
       # Checkout.
       - name: Checkout repository
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       # Setup `R`.
       - name: Setup R
@@ -41,7 +41,27 @@ jobs:
 
       # Run the test coverage excluding specific lines.
       - name: Test coverage
-        env:
-          PROCESSX_NOTIFY_OLD_SIGCHLD: true
-        run: covr::codecov(line_exclusions = list("R/parabar-package.R", "R/UserApiConsumer.R" = c(118:136)))
+        run: |
+          covr::codecov(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(normalizePath(Sys.getenv("RUNNER_TEMP"), winslash = "/"), "package"),
+            line_exclusions = list("R/parabar-package.R", "R/UserApiConsumer.R" = c(118:136))
+          )
         shell: Rscript {0}
+
+      # Show the output of `testthat`.
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      # Upload results on failure.
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v4
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
